---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hearus-front
  labels:
    app.kubernetes.io/name: hearus-front
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hearus-front
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hearus-front
    spec:
      containers:
      - image: 939992775538.dkr.ecr.ap-northeast-2.amazonaws.com/hearus-front-vue:lastest
        name: hearus-front
        ports:
        - containerPort: 80
          name: hearus-front