---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hearus-front
  namespace: default
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app: hearus-front
  template:
    metadata:
      labels:
        app: hearus-front